AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ultimate CloudFormation

Parameters:
  LambdaFunctionName:
    Type: String
    Default: UltimateLambda

Resources:
  StackEventSns:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: StackEventSns
      TopicName: StackEventSns

  ChildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: template_child.yaml
      Parameters:
        StackEventSnsArn: !Ref StackEventSns
        StackName: !Ref AWS::StackName
      NotificationARNs:
        - !Ref StackEventSns
